version: '3.3'

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  php:
    image: php:8-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
      - ./nginx/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9001:9000"
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name : mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./nginx/sql_mode.cnf:/etc/mysql/conf.d/sql_mode.cnf
    environment:
      MYSQL_DATABASE: db_laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel